Bump ruby version
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.6.0. The current ruby
        version is 2.5.0.